language: python
python:
  - "3.9.12"
#setup and install packages
before_install:
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install codecov
  - pip install datetime
# command to run tests
script:
  - python mdstm_testsuite.py
#submit code coverage
after_success:
  - codecov