{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "b3194ebc-8ca3-456e-af15-2e22b87c8893",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Person:\n",
    "    def __init__(self, name):\n",
    "        self.__name = name\n",
    "        \n",
    "    @property\n",
    "    def name(self):\n",
    "        return self.__name\n",
    "    \n",
    "    @name.setter\n",
    "    def name(self, name):\n",
    "        self.__name = name\n",
    "        \n",
    "    @name.deleter\n",
    "    def name(self):\n",
    "        del self.__name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "97cda37c-a17e-42df-bed2-6a856e47c149",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Instructor(Person):\n",
    "    def __init__(self, name, hours=\"not specified\", comm=\"not specified\"):\n",
    "        Person.__init__(self,name)\n",
    "        self.__teaches = []\n",
    "        self.__hours = hours\n",
    "        self.__comm = comm\n",
    "        \n",
    "    @property\n",
    "    def teaches(self):\n",
    "        return self.__teaches\n",
    "    \n",
    "    @property\n",
    "    def hours(self):\n",
    "        return self.__hours\n",
    "    \n",
    "    @property\n",
    "    def comm(self):\n",
    "        return self.__comm\n",
    "    \n",
    "    @teaches.setter\n",
    "    def teaches(self, teach):\n",
    "        self.__teaches.append(teach)\n",
    "        \n",
    "    @hours.setter\n",
    "    def hours(self, hours):\n",
    "        self.__hours = hours\n",
    "        \n",
    "    @comm.setter\n",
    "    def comm(self, comm):\n",
    "        self.__comm = comm\n",
    "        \n",
    "    @teaches.deleter\n",
    "    def teaches(self):\n",
    "        del self.__teaches\n",
    "    \n",
    "    @hours.deleter\n",
    "    def hours(self):\n",
    "        del self.__hours\n",
    "    \n",
    "    @comm.deleter\n",
    "    def comm(self):\n",
    "        del self.__comm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "96431bc1-e744-4a97-9714-1621fe229566",
   "metadata": {},
   "outputs": [],
   "source": [
    "class Student(Person):\n",
    "    def __init__(self, name, sID):\n",
    "        Person.__init__(self,name)\n",
    "        self.__sID = sID\n",
    "        self.__courses = []\n",
    "        \n",
    "    @property\n",
    "    def sID(self):\n",
    "        return self.__sID\n",
    "       \n",
    "    @property\n",
    "    def courses(self):\n",
    "        return self.__courses\n",
    "    \n",
    "    @sID.setter\n",
    "    def sID(self, sID):\n",
    "        self.__sID = sID\n",
    "        \n",
    "    @courses.setter\n",
    "    def courses(self, course):\n",
    "        self.__courses.append(course) \n",
    "        \n",
    "    @sID.deleter\n",
    "    def sID(self):\n",
    "        del self.__sID\n",
    "    \n",
    "    @courses.deleter\n",
    "    def courses(self):\n",
    "        del self.__courses"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
